---
title: "Varicat Ontology Viz"
output: html_notebook
---
```{r}
install.packages("igraph") 
install.packages("ggraph") 
```

```{r}
#library(ggraph) 
library(igraph)
library(cli)
library(dplyr)
#library(tidyverse) 
library(data.tree) # for making the 'ontology' data structure
library(rlang)
library(networkD3) # for making interactive viz
#library(htmlwidgets) # for editing the Javascript code for viz
library(htmltools)
library(stringr)


```

```{r}
# https://stackoverflow.com/questions/13673894/suppress-nas-in-paste
# function to remove NAs and change to ""
paste5 <- function(..., sep = " ", collapse = NULL, na.rm = F) {
  if (na.rm == F)
    paste(..., sep = sep, collapse = collapse)
  else
    if (na.rm == T) {
      paste.na <- function(x, sep) {
        x <- gsub("^\\s+|\\s+$", "", x)
        ret <- paste(na.omit(x), collapse = sep)
        is.na(ret) <- ret == ""
        return(ret)
      }
      df <- data.frame(..., stringsAsFactors = F)
      ret <- apply(df, 1, FUN = function(x) paste.na(x, sep))

      if (is.null(collapse))
        ret
      else {
        paste.na(ret, sep = collapse)
      }
    }
}

c20 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4", "magenta",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "violet", "turquoise",
  "skyblue2", "darkgreen", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid3", "deeppink", "blue1", "steelblue4"
)

```
 
## Read Ontology file with all varicat vars
```{r}
varicat_ontology <- read.csv("varicat_ontology.csv", sep=",", header=TRUE)
# reverse order (only relevant for dendogram)
rev_df <- apply(varicat_ontology, 2, rev) # r
 
# converting the result to dataframe
rev_df <- as.data.frame(rev_df) %>% mutate_all(., list(~na_if(.,"")))
rev_df <- as.data.frame(apply(rev_df,2, str_trim)) %>% arrange(level1) # remove trailing spaces

# subset(rev_df,duplicated(level3)) #check if there are duplicats in lvl 3 except for NAs
```

### Make ontology
```{r}
# create pathString to make the data tree@
rev_df$pathString <- paste5(rev_df$level0, 
                            rev_df$level1, 
                            rev_df$level2, 
                            rev_df$level3,
                            sep = "/", na.rm=TRUE
                            )  
 
ontology <- as.Node(rev_df, na.rm=TRUE) # create data.tree obj
g <- as.igraph(ontology, direction = "climb")  %>% delete_vertices("Variable")  #%>%  delete_edges( c(1:10))  - can be used to delete vertices with string NA
# fc <- cluster_walktrap(g)    

code_temp <- rev_df %>% 
   arrange(level1, level2) %>% 
   mutate(l1_id = (factor(level1))) # factor the domain name to show it as legend names and color vars by the domain it belongs to

code_temp <- bind_rows(code_temp[c(2, 6)], code_temp[c( 3 ,6)], code_temp[c(4,6)]) # create new df grouped by the domain
membership_custom <- cbind(code_temp[2], name = do.call(pmax, c(code_temp[-2], na.rm = TRUE))) %>% distinct() %>% drop_na()  %>% arrange(name) 

d3 <- igraph_to_networkD3(g)  # convert igraph obj to networkd3 obj for viz
membership_custom <-  merge(d3$nodes, membership_custom, on= "name") # merge node df and the new df grouped by domain to get desired color groupings
d3$nodes <-  membership_custom[match(d3$nodes$name, membership_custom$name),] # order vars according to the data.tree obj's original order

# create visualization
fn <- forceNetwork(Links = d3$links, Nodes = d3$nodes ,
             Source = 'source', Target = 'target', NodeID = 'name',  Group = 'l1_id', # get node id and group from d3$node
            opacity = 0.9,  zoom = TRUE, legend = TRUE, linkDistance = 25, radiusCalculation = 1.5, 
             charge = -15,   # node repulsion 
             fontSize = 25, fontFamily = "Calibri", 
             ) 

# JS code for fixing the legend on the top left and avoid zooming effect
htmlwidgets::onRender(fn, jsCode = '
  function (el, x) {
    d3.select("svg").append("g").attr("id", "legend-layer");
    var legend_layer = d3.select("#legend-layer");
    d3.selectAll(".legend")
      .each(function() { legend_layer.append(() => this); });
  }
') %>% saveNetwork(file = 'varicat_ontology.html')

# http://curleylab.psych.columbia.edu/netviz/netviz2.html#/20 
```

# Make non-interactive ggraph 
```{r}
# === Helper function set_color ====
set_color <- function(level1_group, grp_color) {
 level2_3 <- rev_df %>% filter(level1 == level1_group)   %>% dplyr::select(level2, level3) %>% as.list() 
 level2_3 <-  (unlist(level2_3, use.names = FALSE))
 level2_3 <- level2_3[!is.na(level2_3)]  # select level 2 and 3 vars that belong to a given level 1 category
 same_category <- c(level1_group, level2_3)
 V(g)[V(g )$name %in% same_category]$color <- adjustcolor(grp_color, 0.5) # color level 1 and its sub- levels 2 and 3 the same color
 return(g) }

e <- get.edgelist(g,names=FALSE)
l <- qgraph.layout.fruchtermanreingold(e,vcount=vcount(g))

# run for loop to color each category
level1_list<- unique(rev_df$level1) 
for (x in 1:20) {
 g <- set_color(levels(factor(level1_list))[x], c20[x]) 
 } 

tiff("varicat_test.tiff", units="in", width=35, height=35, res=250) 
plot(g, layout= l ,  
     # ==== vertex ====
    vertex.frame.color = "white",
    vertex.size=1.25, 
    vertex.shape="circle",
    # ==== label ====
    vertex.label.cex=0.5, 
    vertex.label.family="Helvetica",
    vertex.label.font=2,
    vertex.label.color="black",
   #  set.vertex.attribute(az, "name", value=paste("y",1:27,sep=""))
     #vertex.label.dist=0.25, 

    # ==== edges ====
    edge.color="grey",                           # Edge color
     edge.width=0.5,
     edge.arrow.size = 0.5 ,
     edge.lty="dotdash",
      #edge.labels=T
    )   
legend("topleft",bty = "n",
       legend=levels(factor(level1_list)), fill= adjustcolor(c20, 0.5), border=NA)
dev.off() 
```
#### Reshape inflammaging df to conform to ontology
```{r}
inflam <- read.csv("inflammaging_varicat.csv", sep=",", header=TRUE)

colnames_inflam <- colnames(inflam) # get col names 
inflam_subset_cols <- colnames_inflam[lapply(colnames_inflam, function(x) length(grep("Please|Is.this|What" ,x,value=FALSE))) == 0] # remove sublevels that are too low in the tree
inflam <- inflam %>% dplyr::select(inflam_subset_cols) %>%  select(-(last_col(offset = 5):last_col()))  %>% 
  select(-head(names(.), 5)) # remove first and last five cols

inflam <- mutate_all(inflam, list(~na_if(.,""))) # remove "" and replace as NAs
num_var_per_level <- data.frame(colSums(!is.na(inflam ))) # how many variables are there in each level? (e.g., in  Physical health -> Physical Measurements ->	Weight)

num_var_per_level<- cbind(rownames(num_var_per_level), data.frame(num_var_per_level, row.names=NULL)) # remove row index, create row index as new col
colnames(num_var_per_level) <- c("old_names", "num_var") # rename cols

inflam_2_cols <- cbind(inflam[1], mycol = do.call(pmax, c(inflam[-1], na.rm = TRUE))) %>% group_by(mycol) %>% arrange(Domain.Main.category.of.the.variable.) #collapse mult columns into 1
 
# inflam_subSet %>% dplyr::select(Comorbidities.type., Physical.health.type.) %>% filter(Physical.health.type. == "Comorbidities", !is.na(Comorbidities.type.)) # 120 vars
# inflam_subSet %>% dplyr::select(Comorbidities.type., Physical.health.type.) %>% filter(Physical.health.type. == "Comorbidities", is.na(Comorbidities.type.)) # 31 vars 
```
### Ontology in short-form/numeric code == Issues due to non-unique node names == 
```{r}
#level1_n <- rev_df %>% group_by(level1) %>% tally() # e.g., Clinical characteristics 
#level2_n <- rev_df %>% group_by(level1, level2) %>% tally() # e.g., Under clinical charac -> Current diagnosis (11), Current inpatient vs outpatient status (1)

# l1 <- rep(LETTERS[1:length(level1_n$n)], as.vector(level1_n$n))
# l2 <- unlist(lapply(level2_n$n, function(x){as.vector(1:x)}))
# l3 <- unlist(lapply(level2_n$n, function(x){as.vector(1:x)}))

code_df <- rev_df %>% dplyr::select(level0, level1, level2, level3)

code_df <- code_df %>% 
  rowwise() %>% 
  arrange(level1, level2) %>% 
  mutate(l1_id = str_replace(level1, "-", " ")) %>%  
  mutate(l1_id = paste(
    unlist(
      lapply((str_split(l1_id, ' ')), function(x){
        str_to_title(str_sub(x, 1, 4))
      })
    ), collapse = ""))   
 
code_df <- code_df %>% 
   arrange(level1, level2) %>% 
   group_by(level1) %>%
   mutate(l2_id = as.numeric(factor(level2)))  

code_df <- code_df %>% 
   group_by(level1, level2) %>%
   mutate(l3_id = as.numeric(factor(level3)))  %>%
     arrange(level1, level2, level3)  

code_df <- code_df %>% ungroup() %>% dplyr::select(level0, l1_id, l2_id, l3_id)
 
code_df$level0 <- (code_df$level0)
 code_df$pathString <- paste5(code_df$level0, 
                            code_df$l1_id, 
                            code_df$l2_id, 
                            code_df$l3_id,
                            sep = "/", na.rm=TRUE
                            )  
 
```


```{r}
all_levels<-read.csv("all_levels_names.csv") 
# level names that do not belong to any categories in the ontology (this is weird, need to check)

inflam_2_cols[!inflam_2_cols$mycol %in% c(all_levels$level2) & 
                 !inflam_2_cols$mycol %in% c(all_levels$level3),] %>% group_by(mycol) %>% tally() 
inflam_2_cols <- inflam_2_cols [!inflam_2_cols$mycol %in% c("Drug name", "Miscellaneous", "Number of conditions", "Severity score"), ]

inflam_2_cols%>% group_by(Domain.Main.category.of.the.variable., mycol) %>% tally()  #=== THIS IS CORRECT ====
 
# looks like these levels are actually level 4 categories -> remove them 
# group by level2 and 3 names and count the number vars in each of levels 
inflam <- inflam_2_cols [!inflam_2_cols$mycol %in% c("Drug name", "Miscellaneous", "Number of conditions", "Severity score"), ] %>% group_by(Domain.Main.category.of.the.variable., mycol) %>% mutate(n= n()) %>% arrange(Domain.Main.category.of.the.variable.)  %>% distinct()

only_level_2 <- inflam[inflam$mycol %in%c(all_levels$level2), ]
only_level_3 <- inflam[inflam$mycol %in%c(all_levels$level3), ]

colnames(only_level_2) <- c("Domain", "level2", "level2_n")
colnames(only_level_3) <- c("Domain", "level3", "level3_n")
# separate level 2 and 3 into different columns
inflam_level_2_3_split <- rbind(only_level_2, only_level_3)

Current_diagnosis_sublevels <- c('Diagnostic group (e.g., Bipolar vs other psychiatric diagnosis or HC)',
  'Other diagnostic specifiers', 
  'Current episode type (e.g., manic/depressed/euthymic/mixed/remitted)', 
  'Most recent affective episode type')
global <- c('Global/screening score')
dep_eps_course <- c('History of psychotic depression', 'History of depression with atypical symptoms', 'Number of depressive episodes')
manic_eps_course <- c('Number of manic episodes')
hypomanic_eps_course <-  c('Number of hypomanic episodes')
mixed_eps_course <- c('Number of mixed episodes')
general_eps_features <- c('Lifetime rapid cycling', 'Seasonality?')
hopsitalizations <- c('Number of psychiatric hospitalizations')
functioning <- c('Rated by others')
c_drug_class <- c('Total psychiatric medications (count)',  'Non-Psychiatric Medications')
ect <- c('Lifetime number of ECTs')
phys_measure <- c('Weight')
comorbidities  <- c('Heart', 'Vascular', 'Renal','Endocrine and breast', 'Respiratory', 'Eyes/ears/ nose/ throat/ and larynx', 'Musculoskeletal and skin', 'Neurologic', 'Liver/pancreas/ and biliary', 'Upper GI','Lower GI', 'Hematopoietic', 'Genitourinary') 

inflam_level_2_3_split <- inflam_level_2_3_split %>% mutate(level2 = case_when(
  level3 %in% Current_diagnosis_sublevels  ~ "Current diagnosis", 
  level3 %in% global ~ "Global",
  level3 %in% dep_eps_course ~ "Depressive episode course",
  level3 %in% manic_eps_course ~ "Manic episode course",
  level3 %in% hypomanic_eps_course ~ "Hypomanic episode features",
  level3 %in% mixed_eps_course ~ "Mixed episode features",
  level3 %in% general_eps_features ~ "General episodic features",
  level3 %in% hopsitalizations ~ "Hopsitalizations",
  level3 %in% functioning ~ "Functioning",
  level3 %in% c_drug_class ~ "Drug class",
  level3 %in% ect ~ "ECT",
   level3 %in% phys_measure ~ "Physical Measurements",
  level3 %in% comorbidities ~ "Comorbidities",
  TRUE ~ level2))
```

```{r}
inflam_combined_n <- cbind(inflam_level_2_3_split[c(1,2,4)], mycol = do.call(pmax, c(inflam_level_2_3_split['level2_n'] , inflam_level_2_3_split['level3_n'], na.rm = TRUE))) %>% arrange(Domain)
inflam_combined_n <- inflam_combined_n %>% mutate(level2 = case_when(Domain == 'Current pharmacological treatment' & level3 == 'Total psychiatric medications (count)' ~ "Current Drug Class",
                                                Domain == 'Current pharmacological treatment' & level3 == 'Non-Psychiatric Medications' ~ "Current Drug Class",
                                                 Domain == 'Current pharmacological treatment' & level2 == 'Drug class' & is.na(level3) ~ "Current Drug Class",
                                                TRUE ~level2)) %>% mutate(level3 = case_when(
                                                  Domain == "Course of non-bipolar psychiatric illness" & level3 == 'Other' ~ "CoNBDpi Other",
                                                  Domain == "Metadata" & level3 == 'Other' ~ "Metadata Other",
                                                  Domain == "Current pharmacological treatment" & level3 == 'Other' ~ "C PT Other",
                                                   TRUE ~level3)) %>% mutate(level2 = case_when(
                                                  Domain == "Course of non-bipolar psychiatric illness" & level3 == 'CoNBDpi Other' ~ "CoNBDpi O.",
                                                  Domain == "Metadata" & level3 == 'Metadata Other' ~ "Metadata O.",
                                                  Domain == "Current pharmacological treatment" & level3 == 'C PT Other' ~ "C PT O.",
                                                   TRUE ~level2))%>% mutate(level3 = str_replace_all(level3, "/", " "), 
                                                                           level2 = str_replace_all(level2, "/", " "), 
                                                                           Domain = str_replace_all(Domain, "/", " ")) %>% distinct()
inflam_combined_n$level0 <- rep("Var", dim(inflam_combined_n)[1])

inflam_combined_n$pathString <- paste5(inflam_combined_n$level0, 
                            inflam_combined_n$Domain, 
                            inflam_combined_n$level2, 
                            inflam_combined_n$level3,
                            sep = "/", na.rm=TRUE
                            )  
 
#inflam_ontology <- FromDataFrameTable(inflam_combined_n, colLevels = list( c("mycol")), na.rm = TRUE)
inflam_ontology <- as.Node( inflam_combined_n)

print(inflam_ontology, "mycol")
g <- as.igraph(inflam_ontology, direction = "climb") # %>% delete_vertices("Variable")  #%>%  delete_edges( c(1:10))  - can be used to delete vertices with string NA
d3 <- igraph_to_networkD3(g) 
# fc <- cluster_walktrap(g)    




inflam_combined_n[duplicated(inflam_combined_n$pathString),]
rev_df
```


 
 

```{r}
# ==== MAKE DENDOGRAM ==== 
#create a data frame
data <- rev_df
#transform it to a edge list!
edges_level0_1 <- data %>% select(level0, level1) %>% unique %>% rename(from=level0, to=level1)

edges_level1_2 <- data %>% select(level1, level2) %>% unique %>% rename(from=level1, to=level2)
edges_level2_3 <- data %>% select(level2, level3) %>% unique %>% rename(from=level2, to=level3)

edges=rbind(
  edges_level0_1,
  edges_level1_2, edges_level2_3)

edges = edges %>% drop_na()

# create a vertices data.frame. One line per object of our hierarchy
vertices = data.frame(
  name = unique(c(as.character(edges$from), as.character(edges$to))) ,
  value = runif(240))
# Now we can plot that
mygraph <- graph_from_data_frame(edges  )

jpeg("varicat_ontology.jpeg", units="in", width=30, height=60, res=200)
ggraph(mygraph, layout = 'dendrogram', circular = FALSE, repel=TRUE , ratio = 0.1, ) +
  geom_edge_diagonal() +
  geom_node_label(aes(label=name  )  )+
  theme_graph(base_family = "Arial" )  +
   theme_void() +  coord_flip()
dev.off()

```
 